language: android
jdk: oraclejdk8
sudo: false

notifications:
    email: false
    
android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
    - yes | sudo sdkmanager --licenses

script: ./gradlew checkstyle pmd
