language: android
jdk: oraclejdk8
sudo: false

notifications:
    email: false
    
android:
  components:
    - platform-tools
    - tools
    - build-tools-28
    - android-28
    - extra-android-m2repository

script: ./gradlew checkstyle pmd
